name: CI Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  gradle:
    strategy:
        os: windows-latest
    runs-on: windows-latest

    steps:
         - uses: actions/checkout@v2
         - name: Set up JDK 11
           uses: actions/setup-java@v1
           with:
               java-version: 11
                description: 'adopt'
         - name: Grant execute permission for gradlew
           run: chmod +x gradlew
         - name: Build with Gradle
           run: ./gradlew build
         - name: Print Message
           run: echo "CI pipeline part finished successfully!"