name: pull request
on:
  pull_request:
      branches: [ master ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
       - name: Build with Gradle
        run: ./gradlew build
